title: "Johann Quenta" 
description: "My personal website" 
theme: minima

author: "Johann Quenta" 

header_pages:
  - index.md
  - research.md
  - teaching.md
  - talks.md
  - cv.md
  - blog.md
  
markdown: kramdown
